---
kind: pipeline
name: default
trigger:
  event: [ push ]

steps:
- name: publish_ecr
  image: plugins/ecr
  settings:
    repo: 474497234551.dkr.ecr.eu-central-1.amazonaws.com/drone/drone-config-changeset-conditional
    region: eu-central-1
    registry: 474497234551.dkr.ecr.eu-central-1.amazonaws.com
    tags:
      - latest
      
  when:
    event:
    - push
    - tag
